### ISSUE TITLE
adição de colaboradores

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/informatica29velhadonatal#1]
confirmem que foram adicionados.

**Comment by drbeco** [comment]
Ahahahaha! Adorei o nome do repositório!

**Comment by iWarhead** [comment]
Confirmado ;)

**Comment by wagner-lucas** [comment]
confirmado.

**Comment by alessonrenato** [comment]
Rafael adicionado, confirma e fecha

**Comment by iWarhead** [comment]
Bem vindo ao lado negro do natal. Que a velha esteja com você.

**Comment by RafaelRSPX** [comment]
kkkkkkkkkkkkk. Adicionado e sincronizado.

**Comment by drbeco** [comment]
**May the gammer be with you.**
