### ISSUE TITLE
Menu para o jogador

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#10]
Galera estava pensando num tipo de menu para que o jogador possa escolher a casa que ele quer fazer sua jogada. Fica mais ou menos assim:
```
0│1│2
─┼─┼─
3│4│5
─┼─┼─
6│7│8
```
Igual ao exemplo do e-mail. O jogador escolhe o número da casa que quer jogar.
 Só que esse tabuleiro é fixo e fica sempre imprimindo antes do tabuleiro do jogo. O que vocês acham?

**Comment by RafaelRSPX** [comment]
Concordo. Acredito que fica melhor para o jogador escolher a casa que ele quer jogar.

**Comment by iWarhead** [comment]
Concordo, assim fica mais simples escolher a jogada.

**Comment by alessonrenato** [comment]
Sim, limitar as opções do usuário reduz os erros de entrada
