### ISSUE TITLE
Menu Tabuleiro

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#11]
Tava testando o programa e vi que o menu tava imprimindo errado:
```
0│1│2│
─┼─┼─
1│2│3│
─┼─┼─
2│3│4│
─┼─┼─
```

**Comment by wagner-lucas** [comment]
Rafael eu adicionei o tabuleiro fixo ao menu e esta imprimindo certo. No commit 66ae1e252aaf5997a228dc9de9bf8bfbc06813a2
