### ISSUE TITLE
função inicializa

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#12]
Galera criei uma função genérica inicializa, porém ainda falta implementa-la.

**Comment by alessonrenato** [comment]
Coloquei a função modo

**Comment by RafaelRSPX** [comment]
Coloquei a função ```comeca``` para escolher quem vai começar a jogar primeiro.

**Comment by RafaelRSPX** [comment]
Correções feitas e função finalizada.
