### ISSUE TITLE
Otimizar as escolhas do jogador.

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/informatica29velhadonatal#14]
Poderia ser melhor colocar a impressão das escolhas do jogador em uma função separada, podemos precisar desse procedimento pra o menu do jogo em si.

**Comment by RafaelRSPX** [comment]
Concordo. Também acredito que iremos precisar da impressão para o menu do jogo. #11. #10

**Comment by wagner-lucas** [comment]
Boa ideia alesson,porque poderemos precisar dessa impressão em outras funções.

**Comment by alessonrenato** [comment]
ideia implementada.
