### ISSUE TITLE
Bug no buffer do stdin

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#16]
Tava testando o programa e nas opções, caso o jogador escreva uma opção inválida, o programa aceita a opção e passa para a escolha das outras opções:
```
Selecione o modo de jogo
1-Humano X Humano
2-Humano X Computador
3-Computador X Computador
s

Quem joga primeiro?
h- jogador
c- computador
h

Selecinone a dificuldade:
1-Facil
2-Medio
3-Dificil
3

MODO:
Humano X Computador

Quem comeca?
Humano

DIFICULDADE:
Dificil
```

**Comment by iWarhead** [comment]
E caso você use um numero diferente de 123 no modo de jogo, ele simplesmente não aceita mais nada. O mesmo funciona pra qualquer caracter errado nas outras opções.

**Comment by iWarhead** [comment]
Acredito que possa ser resolvido através de um laço, que caso o usuário digite algo inválido, seja mostrado um printf e o programa peça os dados novamente.

**Comment by RafaelRSPX** [comment]
Acredito que corrigi o bug no commit: c9d69f430f6bf38f1b51bed9817d74d646a19439. Adicionei um ```getchar();``` antes do ```scanf();``` e incializei a variável com 0.
