### ISSUE TITLE
Opções do jogador

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#17]
Pessoal, as escolhas do jogador estão com um problema bem chato. O jogador não pode errar a escolha da opção, se errar o programa não aceita as opções mesmo quando digita uma opção válida.

**Comment by RafaelRSPX** [comment]
Alterei a posição do ```getchar();``` mostrado no seguinte commit: 00ee71aa8aba660ff74f29ed3dd8c9bb8b5a4301

O problema dessa solução é que se o jogador escrever vários carácteres inválidos e se um desses caracteres tiver um carácter válido como, o programa aceita e passa para a próxima opção.
