### ISSUE TITLE
Tabuleiro fixo

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#18]
Gente eu adicionei o tabuleiro fixo ao menu, caso alguém pense em um jeito melhor de deixar o menu, ai tiramos o tabuleiro fixo. O que vocês acham?.  #10

**Comment by alessonrenato** [comment]
sim, deixar as opções do usuário restritas aos numeros da casa.

**Comment by iWarhead** [comment]
Certo. Acredito que o tabuleiro fixo está interessante assim

**Comment by RafaelRSPX** [comment]
Ok. Fica melhor desse jeito. :+1: E pelo que vi, todos concordaram.
