### ISSUE TITLE
Parâmetros da função nível

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/informatica29velhadonatal#19]
Caros, nas funções nivelfacil; nivelmedio e niveldificil talvez não seja necessário receber o parâmetro da tabela, pois ela já é uma variável global dentro da estrutura "velha".

**Comment by wagner-lucas** [comment]
Certo alesson, eu percebi isso quando estava fazendo nivelfacil, fica até melhor de trabalhar desse jeito.

**Comment by RafaelRSPX** [comment]
Isso mesmo. Também não acho necessário passar essa variável para as funções.

**Comment by iWarhead** [comment]
Também percebi isso. Deixar na forma de estrutura fica mais fácil

**Comment by drbeco** [comment]
Não usar `structs`!

**Comment by RafaelRSPX** [comment]
Já que é necessário não utilizar estrutura, vou fechar essa issue.
