### ISSUE TITLE
Função mododejogo

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#21]
Implementei a função ```mododejogo``` para separar os tipos de modo na função main. Falta implementar os funções ```humanoxhumano()```, ```humanoxcomputador()``` e ```computadorxcomputador()```.

**Comment by iWarhead** [comment]
Implemente a função humanoxhumano e adicionei a função jogadorX.

**Comment by drbeco** [comment]
Tenho a impressão que essas funções não estão muito bem organizadas.

Por que 3 funções? O que é a "abstração" de código que tem em `humanoxcomputador` e é diferente de `humano` e `computador`? Alguém me explica e justifica o raciocínio?

**Comment by RafaelRSPX** [comment]
Era para deixar o código mais organizado professor. Uma dessas funções iria ser selecionada num switch dependendo do modo de jogo que o jogador escolher. Mas essas funções iriam utilizar estrutura, sendo assim, acredito que iremos descartar essas funções e implementar outras ou apenas uma.

**Comment by RafaelRSPX** [comment]
Função retirada no commit de @wagner-lucas : e1540fd046ae86c5ab190885bce967de3b598934
