### ISSUE TITLE
Funcao jogador(X/O)

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#22]
A função ```jogadorX``` vai executar um comando que o jogador der dependendo da casa que escolher. Mas a função ```jogadorO``` também vai executar os mesmos comandos, acredito que fique melhor otimiza-lo para uma função que execute o comando.

**Comment by alessonrenato** [comment]
Sim, pois eles podem tanto ser Computador como humano dependendo da configuração do jogo.

**Comment by drbeco** [comment]
Uma função é uma coleção de código para executar uma mesma tarefa várias vezes.

Se uma hora `jogadorX` é para rodar um código de humano, outra hora `jogadorX` deve executar código para computador, então `jogadorX` não é uma boa escolha para uma função.

**Comment by RafaelRSPX** [comment]
De fato professor. Retiraremos do código.
