### ISSUE TITLE
Quadrado mágico

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/informatica29velhadonatal#24]
Vocês sabem o que é na matemática um **quadrado mágico**?

E qual a relação que tem com o jogo-da-velha?

![image](https://cloud.githubusercontent.com/assets/5805111/11985064/d6dd5430-a99f-11e5-95be-b929a642fd23.png)

**Comment by RafaelRSPX** [comment]
Pelo que pesquisei agora professor, é uma distribuição de números em progressão aritmética que, nesse caso, a soma dos números na mesma linha ou coluna ou a soma dos números na diagonal vai dar 15. 
Mas não sei qual a relação com o jogo-da-velha.

**Comment by wagner-lucas** [comment]
Professor de acordo com minha pesquisa, eu encontrei basicamente isso o que rafael falou. E eu acho que a relação disso com o jogo da velha é exatamente a soma dos números na mesma linha ou coluna ou nas diagonais sejam iguais, se o jogar conseguir fazer um desses casos, significa que ele é o vencedor.

**Comment by RafaelRSPX** [comment]
Pelo que pesquisei, para construirmos esse quadrado mágico devemos ver grupos de números sem repetição que somados dê 15.

Se eu tenho um conjunto {1, 2, 3, 4, 5, 6, 7, 8, 9}
Indo de forma intuitiva, começando pelo número 1, vemos que podemos fazer dois conjuntos de números que somados deem 15: (1, 5, 9) e (1, 6, 8). 
Seguindo a mesma linha de raciocínio, fazemos o mesmo procedimento com o número 2: (2, 4, 9), (2, 5, 8) e (2, 6, 7). E assim por diante. Isso resulta nos seguintes conjuntos:
**1 -**
1, 5, 9
1, 6, 8

**2-**
2, 4, 9
2, 5, 8
2, 6, 7

**3-**
3, 4, 8
3, 5, 7

**4-**
4, 2, 9
4, 3, 8
4, 5, 7

**5-**
5, 1, 9
5, 2, 8
5, 3, 7
5, 4, 6

**6-**
6, 1, 9
6, 2, 7
6, 4, 5

**7-**
7, 2, 6
7, 3, 5

**8-**
8, 1, 6
8, 2, 5
8, 3, 4

**9-**
9, 1, 5
9, 2, 4

![sem titulo](https://cloud.githubusercontent.com/assets/13755711/12012745/e523f6c6-ace1-11e5-8512-d45720082b8e.png)

Pelo quadrado, a célula central precisa de um número que tenha 4 grupos que somados dê 15. O único que tem 4 grupos é o 5, então ele deve ficar no meio. Nos vértices, precisamos de números que tenham 3 grupos, ou seja, o 2, 4, 6 e 8. 
Com isso, o quadrado pode ficar assim: 

![sem titulo](https://cloud.githubusercontent.com/assets/13755711/12012765/8c414bd4-ace2-11e5-977c-17a5cf4f1a4a.png)

Os números dos vértices podem ser organizados em outras formas, desde que os números sejam 2, 4, 6 e 8. E para completar é só por os restantes dos números tomando cuidado para que a soma seja sempre 15.

**Comment by RafaelRSPX** [comment]
O quadrado mágico pode ter vários resultados: 

![sem titulo](https://cloud.githubusercontent.com/assets/13755711/12012789/4444c864-ace3-11e5-8227-f081f812902c.png)
