### ISSUE TITLE
Combinação C9,3

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/informatica29velhadonatal#25]
A combinação C9,3 indica de quantas maneiras diferentes se pode pegar 3 itens de um grupo de nove. 

Por exemplo, um grupo com as 9 primeiras letras do alfabeto: `{a, b, c, d, e, f, g, h, i}`. As combinações seriam:

```
abc
abd
abe
abf
abg
abh
abi
acd
...
aci
ade
...
adi
...
bcd
...
bci
...
ghi
```

Na combinação a ordem não importa. Portanto escolher `abc` é o mesmo que escolher `bca`, por exemplo.

Para calcular a combinação `C9,3` usa-se o binomial `(9 3) = 9! / (3! * (9-3)!) = 84` possibilidades.

Se ao invés de letras do alfabeto, tivermos números de `{0, 1, 2, 3, 4, 5, 6, 7, 8}` o raciocínio é o mesmo. As soluções seriam `S={012, 013, ... 018, 023, ..., 678}`

Faça uma função que imprima todas as 84 soluções de combinações possíveis.

Pergunta: como essa função poderá ser usada no jogo-da-velha em conjunto com o quadrado mágico?

**Comment by RafaelRSPX** [comment]
Implementei o seguinte programa:
```
#include <stdlib.h>
#include <stdio.h>

#define MAXVET 9 /* numero de elementos */

int main(void)
{
    int numero[MAXVET]={0, 1, 2, 3, 4, 5, 6, 7, 8}; /* conjunto de numeros */
    int a, b, c;
    int i;

    /* impressao dos elementos do conjunto */
    printf("Combinacoes 9,3 de { ");
    for(i=0; i<MAXVET; i++)
        printf("%d ", numero[i]);
    printf("}\n");
   
    /* processamento */
    for(a=0;a<(MAXVET-2);a++)
        for(b=(a+1);b<(MAXVET-1);b++)
            for(c=(b+1);c<MAXVET;c++)
                printf("%d%d%d\n", numero[a], numero[b], numero[c]);

    return EXIT_SUCCESS;
}
```
Tendo como resultado:
```
Combinacoes 9,3 de { 0 1 2 3 4 5 6 7 8 }
012
013
014
015
016
017
018
023
024
025
026
027
028
034
035
036
037
038
045
046
047
048
056
057
058
067
068
078
123
124
125
126
127
128
134
135
136
137
138
145
146
147
148
156
157
158
167
168
178
234
235
236
237
238
245
246
247
248
256
257
258
267
268
278
345
346
347
348
356
357
358
367
368
378
456
457
458
467
468
478
567
568
578
678
```

**Comment by RafaelRSPX** [comment]
"Filtrando" os resultados para valores que somados dê 15, as soluções reduzem para: 
```
Combinacoes 9,3 de { 0 1 2 3 4 5 6 7 8 }
078
168
258
267
348
357
456
```
