### ISSUE TITLE
Feliz Natal!

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/informatica29velhadonatal#26]
**Feliz Natal!**

Um excelente dia de Natal para todos!

**Comment by RafaelRSPX** [comment]
Um Feliz Natal para o senhor também professor. Desejo um feliz nata à todos.

**Comment by wagner-lucas** [comment]
Feliz Natal para o senhor também. 
Feliz Natal grupo.

**Comment by iWarhead** [comment]
Feliz natal senhores
