### ISSUE TITLE
Ponteiro

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#28]
Como não podemos utilizar variáveis globais, achei necessário adicionar nas funções ```imprimeTabuleiro``` e  ```preenchezero``` ponteiros para endereço do tabuleiro como mostrado no commit d00a6115d34ae745c5dd6f5be398b7d037f50e83 e a013b979701403f4cf8657085cf3e9c89fe2265a. Fiz testes em um arquivo externo e vi que estava funcionando. O que vocês acham?

**Comment by wagner-lucas** [comment]
Certo rafael, como estamos trabalhando com endereço é necessário usar ponteiro  e eu acho que vamos ter que fazer o mesmo em outras funções também.
