### ISSUE TITLE
Níveis de jogo

### ISSUE THREAD

**Issue by iWarhead** [alessonrenato/informatica29velhadonatal#29]
Caros, precisamos criar as funções para os níveis médio e difícil, como iremos trabalhar nelas?

**Comment by alessonrenato** [comment]
Os ajustes foram finalizados, podemos focar nelas agora.

**Comment by wagner-lucas** [comment]
A função nível médio eu comecei a fazer e com a finalização da função ```segundajogada```, o raciocínio dessa função esta pronto, fica faltando nível difícil.

**Comment by RafaelRSPX** [comment]
A issue #43 tem uma linha de raciocínio.
