### ISSUE TITLE
Função main

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#37]
Função ```main``` está muito longa. Tem como reduzi-la?

**Comment by iWarhead** [comment]
Acho que podemos criar uma função inicializa para reduzir bastante a main.

**Comment by wagner-lucas** [comment]
Concordo com arthur, vai diminuir a ```main``` e fica mais fácil de analisar se tem alguma coisa errada.

**Comment by RafaelRSPX** [comment]
Resolvido. #38
