### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#4]
Galera criei o arquivo AUTHORS, adicionem seu nome nele.

**Comment by iWarhead** [comment]
O arquivo AUTHORS não é .md?

**Comment by drbeco** [comment]
No.

**Comment by drbeco** [comment]
Faltou label aqui nesse issue. Todos tem que ter label e milestone

**Comment by iWarhead** [comment]
Adicionei meu nome

**Comment by alessonrenato** [comment]
Adicionei o meu.
