### ISSUE TITLE
Erro ao informar quem ganhou

### ISSUE THREAD

**Issue by iWarhead** [alessonrenato/informatica29velhadonatal#40]
Senhores, independente de quem ganhar o programa (se alguem ganhar), a mensagem mostrada sempre é "DEU VELHA!". O erro provavelmente está na função inicializa, gostaria de ajuda para resolvê-lo.

**Comment by alessonrenato** [comment]
Achei, era um -1 inconveniente.

**Comment by alessonrenato** [comment]
Corrigido no comit 760aa02bf239720077ab72a91e2a6d1791cc26ad
