### ISSUE TITLE
nivel medio

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/informatica29velhadonatal#42]
Amigos eu implementei as condições para a primeira jogada no nível médio, porem esse nível ainda esta incompleto, falta determinar como serão as próximas jogadas do computador, que no código esta ```segunda jogada```.

**Comment by iWarhead** [comment]
Criei a função segunda jogada.

**Comment by iWarhead** [comment]
Resolvido no commit 6f09bbe.
