### ISSUE TITLE
Niveis

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#43]
Pensei na seguinte lógica, no nível médio o computador tenta ganhar apenas completando as casas. Se não dá para completar as casas, ele joga aleatoriamente. 
Para o nível difícil, ele tenta fechar o jogador e tenta completar as casas para vencer.

**Comment by iWarhead** [comment]
Também estava pensando assim, acho uma boa idéia

**Comment by iWarhead** [comment]
A função segundajogada criada no commit 6f09bbe segue esta linha de raciocinio.

**Comment by alessonrenato** [comment]
adicionei a funcao niveldificil no comit 64cecfafcc45aeb476da40e90bb7eaa6eee0a27e
