### ISSUE TITLE
Pergunta jogar novamente

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#48]
O programa sempre fica perguntando se quero jogar novamente, mesmo nas minhas jogadas.

**Comment by alessonrenato** [comment]
Acontece tanto em Jogador X Computador e em Computador X Computador.

**Comment by RafaelRSPX** [comment]
implementei um nova função ```jogarnovamente``` para perguntar se o jogador quer sair do jogo. Mostrado no commit: 51c47d05944bb889f4547b26238101328e2ffd1e
