### ISSUE TITLE
Realese v1.0

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/informatica29velhadonatal#50]
Caros, 

Pelos testes que fiz, o programa parece está finalizado. Concordam em liberar a versão v1.0?

**Comment by alessonrenato** [comment]
Meus teste aqui, tudo estava funncionando, por mim podemos encerrar.

**Comment by iWarhead** [comment]
Meus testes funcionam.
*All systems are go*

**Comment by alessonrenato** [comment]
Podemos ter o Liftoff houston?

**Comment by wagner-lucas** [comment]
Concordo, eu testei e o programa esta funcionando.

**Comment by alessonrenato** [comment]
T minus 10 and counting...

**Comment by alessonrenato** [comment]
Tag v1.0 lançada
