### ISSUE TITLE
Meta v0.1

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/informatica29velhadonatal#6]
Todas as tarefas da primeira meta foram encerradas, vocês acham pertinente já encerrá-la hoje ou deixamos pra amanhã?

**Comment by RafaelRSPX** [comment]
Acredito que seja melhor fechar hoje. Todos os arquivos foram adicionado, assim como os colaboradores.

**Comment by iWarhead** [comment]
Pode ser hoje, aí já podemos começar o programa, o quanto mais a gente fizer antes do natal, melhor.

**Comment by wagner-lucas** [comment]
concordo em fechar hoje.

**Comment by alessonrenato** [comment]
como todos concordam release adicionado, meta encerrada.

**Comment by iWarhead** [comment]
Como já atingimos a meta, hora de dobrar a meta. ¯\_(ツ)_/¯

**Comment by RafaelRSPX** [comment]
:+1: exato
